FROM jenkins/jenkins:lts-jdk11

USER root

# .NET Core deps
RUN apt-get update && apt-get install -y wget ca-certificates openssl zlib1g

# .NET Core
RUN wget https://dot.net/v1/dotnet-install.sh  && \
    chmod +x dotnet-install.sh && \
    ./dotnet-install.sh

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="true" \
    PATH="${PATH}:/root/.dotnet"